### PR TITLE
Refactor existing unit tests

### PR DESCRIPTION
**Pull request by Apollogeist**
Refactored unit tests for UserAccount and Section models. Let me know what you guys think.

### CODE REVIEW

**Comment by SleepingLink1** [comment]
The code looks good. Thanks!

**Comment by ConnorBrhely** [comment]
Code looks good man!

**Comment by Apollogeist** [comment]
Alright, I merged it. Feel free to contact if you need my help with any conflicts 👍

**Review by applesandoranges15 — COMMENTED** [review]
Looks good to me. New test cases cover more edge cases.

**Pull request merged**
